version: '3.0'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    volumes:
      - ./server:/usr/multi-snake
